import type { Doctor, Department, Testimonial, FAQ } from './types';

export const DOCTORS: Doctor[] = [
  {
    id: 'd1',
    name: 'Dr. Sarah Mitchell',
    specialty: 'Cardiologist',
    department: 'Cardiology',
    qualification: 'MD, FACC, DM Cardiology',
    experience: 14,
    rating: 4.9,
    reviews: 312,
    patients: 2400,
    fee: 85,
    available: true,
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&auto=format',
    hospital: 'MediBook General Hospital',
    bio: 'Dr. Mitchell specializes in interventional cardiology and heart failure management with over 14 years of clinical experience.',
    gender: 'Female',
    languages: ['English', 'Spanish'],
    awards: ['Best Cardiologist 2023', 'Excellence in Patient Care'],
  },
  {
    id: 'd2',
    name: 'Dr. James Okafor',
    specialty: 'Neurologist',
    department: 'Neurology',
    qualification: 'MD, PhD Neuroscience, FAAN',
    experience: 11,
    rating: 4.8,
    reviews: 245,
    patients: 1850,
    fee: 90,
    available: true,
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&auto=format',
    hospital: 'MediBook General Hospital',
    bio: 'Specialist in stroke management, epilepsy, and neurodegenerative diseases. Published researcher with 40+ peer-reviewed papers.',
    gender: 'Male',
    languages: ['English', 'French', 'Yoruba'],
    awards: ['Neurology Excellence Award 2022'],
  },
  {
    id: 'd3',
    name: 'Dr. Priya Sharma',
    specialty: 'Pediatrician',
    department: 'Pediatrics',
    qualification: 'MD Pediatrics, Fellowship AIIMS',
    experience: 9,
    rating: 4.9,
    reviews: 521,
    patients: 3200,
    fee: 70,
    available: true,
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop&auto=format',
    hospital: 'MediBook General Hospital',
    bio: 'Dedicated to children health from newborns to adolescents. Special interest in developmental pediatrics and vaccination.',
    gender: 'Female',
    languages: ['English', 'Hindi'],
    awards: ['Pediatric Care Award 2023', 'Top Doctor 2022'],
  },
  {
    id: 'd4',
    name: 'Dr. Robert Chen',
    specialty: 'Orthopedic Surgeon',
    department: 'Orthopedics',
    qualification: 'MS Orthopedics, Fellowship Sports Medicine',
    experience: 16,
    rating: 4.7,
    reviews: 189,
    patients: 1500,
    fee: 100,
    available: true,
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&auto=format',
    hospital: 'MediBook General Hospital',
    bio: 'Expert in joint replacement, sports injuries, and minimally invasive orthopedic procedures.',
    gender: 'Male',
    languages: ['English', 'Mandarin'],
    awards: ['Surgical Excellence Award 2021'],
  },
  {
    id: 'd5',
    name: 'Dr. Amara Patel',
    specialty: 'Dermatologist',
    department: 'Dermatology',
    qualification: 'MD Dermatology, MRCP',
    experience: 8,
    rating: 4.8,
    reviews: 398,
    patients: 2800,
    fee: 75,
    available: false,
    image: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop&auto=format',
    hospital: 'MediBook General Hospital',
    bio: 'Specializes in medical and cosmetic dermatology, acne, psoriasis, and skin cancer screening.',
    gender: 'Female',
    languages: ['English', 'Gujarati'],
    awards: ['Derm Excellence 2023'],
  },
  {
    id: 'd6',
    name: 'Dr. Michael Torres',
    specialty: 'General Physician',
    department: 'General Medicine',
    qualification: 'MBBS, MD Internal Medicine',
    experience: 12,
    rating: 4.6,
    reviews: 634,
    patients: 4100,
    fee: 55,
    available: true,
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&auto=format',
    hospital: 'MediBook General Hospital',
    bio: 'Comprehensive primary care physician focused on preventive medicine, chronic disease management, and patient wellness.',
    gender: 'Male',
    languages: ['English', 'Spanish', 'Portuguese'],
    awards: ['Primary Care Excellence 2022'],
  },
];

export const DEPARTMENTS: Department[] = [
  { id: 'dep1', name: 'Cardiology', icon: 'Heart', color: '#EF4444', count: 4, description: 'Heart & vascular care' },
  { id: 'dep2', name: 'Neurology', icon: 'Brain', color: '#8B5CF6', count: 3, description: 'Brain & nervous system' },
  { id: 'dep3', name: 'Pediatrics', icon: 'Baby', color: '#10B981', count: 5, description: "Children's health" },
  { id: 'dep4', name: 'Orthopedics', icon: 'Bone', color: '#F97316', count: 4, description: 'Bones & joints' },
  { id: 'dep5', name: 'Dermatology', icon: 'Stethoscope', color: '#06B6D4', count: 3, description: 'Skin & hair' },
  { id: 'dep6', name: 'General Medicine', icon: 'Activity', color: '#2563EB', count: 6, description: 'Primary care' },
  { id: 'dep7', name: 'Ophthalmology', icon: 'Eye', color: '#EC4899', count: 2, description: 'Eye care' },
  { id: 'dep8', name: 'ENT', icon: 'Ear', color: '#14B8A6', count: 3, description: 'Ear, nose & throat' },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Emily Watson',
    role: 'Patient',
    text: 'MediBook made booking my appointment incredibly easy. The slot system is transparent and I love seeing real-time availability. Highly recommended!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&auto=format',
  },
  {
    name: 'David Kim',
    role: 'Patient',
    text: 'The QR code receipt feature is fantastic. I can track all my appointments in one place. The doctors here are excellent professionals.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&auto=format',
  },
  {
    name: 'Maria Santos',
    role: 'Patient',
    text: 'Fast, reliable, and professional. I booked with Dr. Sharma for my son and the experience was seamless. The UI is so intuitive!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&auto=format',
  },
];

export const FAQS: FAQ[] = [
  { q: 'How do I book an appointment?', a: 'Login or register, browse available doctors, select your preferred doctor, choose an available time slot for today, and confirm your booking.' },
  { q: 'Can I book appointments for future dates?', a: 'Currently, MediBook only supports same-day appointments. You can book slots from 9:00 AM to 6:00 PM for today only.' },
  { q: 'What is the maximum appointments per slot?', a: 'Each hourly slot accommodates a maximum of 3 patients. Slots display remaining capacity in real-time.' },
  { q: 'How do I cancel my appointment?', a: 'Go to My Appointments in your dashboard, find the appointment, and click Cancel. Cancellations are free up to 30 minutes before the slot.' },
  { q: 'Is my data secure?', a: 'Yes, MediBook uses enterprise-grade encryption for all patient data and follows HIPAA compliance guidelines.' },
  { q: 'Can I download my appointment receipt?', a: 'Yes! After booking, you will receive a QR code and can download a PDF receipt from the Booking Success screen or My Appointments.' },
];

export const TIME_SLOTS = [
  { start: '09:00', end: '10:00', label: '09:00-10:00 AM' },
  { start: '10:00', end: '11:00', label: '10:00-11:00 AM' },
  { start: '11:00', end: '12:00', label: '11:00-12:00 AM' },
  { start: '12:00', end: '13:00', label: '12:00-01:00 PM' },
  { start: '13:00', end: '14:00', label: '01:00-02:00 PM' },
  { start: '14:00', end: '15:00', label: '02:00-03:00 PM' },
  { start: '15:00', end: '16:00', label: '03:00-04:00 PM' },
  { start: '16:00', end: '17:00', label: '04:00-05:00 PM' },
  { start: '17:00', end: '18:00', label: '05:00-06:00 PM' },
];

export const generateAppointmentId = () =>
  'MB' + Date.now().toString(36).toUpperCase().slice(-6);
